applications/urls.py
from django.urls import path

from applications import views

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("create", views.CreateView.as_view(), name="create"),
    path("list", views.ListView.as_view(), name="list"),
    path("<int:pk>/delete", views.DeleteView.as_view(), name="delete"),
]

bidnamic/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("applications.urls")),
    path("", include("users.urls")),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users import views

urlpatterns = [
    path("login", views.CustomLoginView.as_view(), name="login"),
    path("signup", views.SignupView.as_view(), name="signup"),
    path("logout", LogoutView.as_view(), name="logout"),
]

applications/models.py
from django.db import models


class Application(models.Model):
    HIGH, MEDIUM, LOW = range(3)
    BIDDING_SETTING_CHOICES = (
        (HIGH, "High"),
        (MEDIUM, "Medium"),
        (LOW, "Low"),
    )
    title = models.CharField(max_length=100)
    first_name = models.CharField(max_length=150)
    surname = models.CharField(max_length=150)
    date_of_birth = models.DateField(verbose_name="Date of birth")
    company_name = models.CharField(max_length=150)
    address = models.TextField()
    telephone = models.CharField(max_length=15)
    bidding_settings = models.SmallIntegerField(choices=BIDDING_SETTING_CHOICES)
    google_account_ads_id = models.CharField(
        verbose_name="Google Ads Account ID", max_length=200
    )
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

applications/forms.py
from datetime import date

from django import forms
from django.core.exceptions import ValidationError

from applications.models import Application


class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = "__all__"
        widgets = {
            "date_of_birth": forms.DateInput(attrs={"type": "date"}),
            "address": forms.Textarea(attrs={"rows": "2"}),
        }

    def clean_date_of_birth(self):
        birthdate = self.cleaned_data["date_of_birth"]
        today = date.today()
        # get age, difference between today and birthdate
        age = (
            today.year
            - birthdate.year
            - ((today.month, today.day) < (birthdate.month, birthdate.day))
        )
        if age < 18:
            raise ValidationError("You must be 18 years old or older to fill this form")

        return birthdate

    def clean_google_account_ads_id(self):
        google_account_ads_id = self.cleaned_data["google_account_ads_id"]
        if len(google_account_ads_id) != 10:
            raise ValidationError("Google account ID must be 10 digits")

        return google_account_ads_id

applications/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import View, generic

from applications.forms import ApplicationForm
from applications.models import Application


class IndexView(generic.TemplateView):
    """Landing page view"""

    template_name = "applications/index.html"


class CreateView(LoginRequiredMixin, View):
    """Create an applicatiom"""

    login_url = "/login"
    redirect_field_name = "next"
    template_name = "applications/create_applications.html"
    form_class = ApplicationForm

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {"form": form})

    def post(self, request):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(
                request, "Application submitted successfully", extra_tags="success"
            )
            return redirect("list")
        messages.error(request, "Please correct the errors below", extra_tags="danger")
        return render(request, self.template_name, {"form": form})


class ListView(View):
    """List all applications"""

    template_name = "applications/list_applications.html"
    paginate_by = 10

    def get(self, request):
        applications = Application.objects.all().order_by("-created_at")

        paginator = Paginator(applications, self.paginate_by)
        page = self.request.GET.get("page")
        try:
            applications = paginator.page(page)
        except PageNotAnInteger:
            # if page is not an intger deliver the first page
            applications = paginator.page(1)
        except EmptyPage:
            #  if page is out of range deliver last page of results
            applications = paginator.page(paginator.num_pages)

        return render(request, self.template_name, {"applications": applications})


class DeleteView(LoginRequiredMixin, generic.DeleteView):
    """Delete applications"""

    model = Application
    login_url = "/login"
    redirect_field_name = "next"
    success_url = reverse_lazy("list")

    def delete(self, request, *args, **kwargs):
        response = super().delete(request, *args, **kwargs)

        messages.success(
            request, "Application deleted successfully", extra_tags="success"
        )
        return response

applications/templates/applications/alerts.html
<div class="row">
   <div class="col-lg-8 mx-auto ">
        {% if messages %}
        <ul style="list-style: none;" class="text-center mb-2 alert">
            {% for message in messages %}
            <li id="message" class="alert alert-{{ message.tags }} ">{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
</div>

applications/templates/applications/application_confirm_delete.html
{% extends 'base.html' %}


{% block content %}


    <div class="container">

        <div class="row mt-5">
            <div class="col-lg-8 mx-auto">

				<form method="post">{% csrf_token %}

				<h5 class="mb-3">Are you sure you want to delete "{{ object }}"?</h5>

					<input class="btn btn-danger" type="submit" value="Confirm">
				</form>


            </div>
        </div>

    </div>


{% endblock content %}

applications/templates/applications/create_applications.html
{% extends 'base.html' %}
{% load crispy_forms_tags  %}


{% block content %}
    <div id="intro" class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto">

                <h3 class="text-center mt-4 text-primary">Submit An Application</h3>

                <h5 class="text-center mt-4"><a class="btn btn-primary font-weight-bold" href="{% url 'list' %}">See All Applications</a> </h5>

                <br>

                    <div class="col-lg-8 mx-auto ">
                        {% if messages %}
                        <ul style="list-style: none;" class="text-center mb-2 alert">
                            {% for message in messages %}
                            <li id="message" class="alert alert-{{ message.tags }} ">{{ message }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                    </div>

                <form style="border: 0.5px solid grey" class="p-3" method="post" action="{% url 'create' %}" enctype="multipart/form-data">
                    {% csrf_token %}

                    {{ form|crispy }}

                <button type="submit" id="submit" class="btn btn-block btn-primary">Submit</button>

                </form>

            </div>


        </div>
    </div>

 <br> <br> <br>
{% endblock content %}

applications/templates/applications/index.html
{% extends 'base.html' %}
{% load crispy_forms_tags  %}


{% block content %}
    <div id="intro" class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto">

                <h3 class="text-center my-5 text-primary">Welcome To Bidnamic Multipart Form Wizard</h3>

                {% include 'applications/alerts.html' %}

                <h5 class="text-center mt-4"><a class="btn btn-primary font-weight-bold" href="{% url 'create' %}">Submit An Application</a> </h5>
                <h5 class="text-center mt-4"><a class="btn btn-primary font-weight-bold" href="{% url 'list' %}">See All Applications</a> </h5>

            </div>


        </div>
    </div>


{% endblock content %}

applications/templates/applications/list_applications.html
{% extends 'base.html' %}


{% block content %}


    <div class="container">

        <div class="row">
            <div class="col-lg-8 mx-auto">
                <h3 class="text-center mt-4 text-primary">All Applications</h3>
                <h5 class="text-center my-5"><a class="btn btn-primary font-weight-bold" href="{% url 'create' %}">Submit New Application</a> </h5>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-8 mx-auto ">
                {% if messages %}
                <ul style="list-style: none;" class="text-center mb-2 alert">
                    {% for message in messages %}
                    <li id="message" class="alert alert-{{ message.tags }} ">{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
        </div>

    </div>


    <!-- table -->
    <div  class="container-fluid">

        <div class="table-responsive mb-5">
            <table id="wishes" class="table  table-striped table-hover">
                <caption>List of applications</caption>

                <thead class="alert-info">
                    <tr>
                        <th scope="col">Title</th>
                        <th scope="col">First name</th>
                        <th scope="col">Surname</th>
                        <th scope="col">Date of birth</th>
                        <th scope="col">Company name</th>
                        <th scope="col">Telephone</th>
                        <th scope="col">Bidding settings</th>
                        <th scope="col">Ads ID</th>
                        <th scope="col">Created At</th>
                        <th scope="col">Delete</th>
                    </tr>
                </thead>

                <tbody>
                    {% for app in applications %}
                    <tr>
                        <td>{{ app.title }}</td>
                        <td>{{ app.first_name }}</td>
                        <td> {{ app.surname }}</td>
                        <td>{{ app.date_of_birth }}</td>
                        <td>{{ app.company_name }}</td>
                        <td>{{ app.telephone }}</td>
                        <td>{{ app.get_bidding_settings_display }}</td>
                        <td>{{ app.google_account_ads_id }}</td>
                        <td>{{ app.created_at }}</td>
                        <td>

                            <a href="{% url 'delete' app.pk %}" class="delete btn btn-sm btn-danger" >
                                <i class="fas fa-trash"></i> Delete
                            </a>
                        </td>
                    </tr>

                    {% endfor %}
                </tbody>

            </table>
        </div>
        <!--  table-responsive -->

            {% if not applications %}

            <h4> No applications found </h4>

            {% endif %}

    </div>
    <!-- container -->


    <!-- Pagination -->
    {% include 'applications/pagination.html' with posts=applications %}


{% endblock content %}

applications/templates/applications/pagination.html
<div class="row">
    <div class="col-md-12">

    {% if posts.has_other_pages %}
        <ul class="pagination justify-content-center mt-1">

        {% if posts.has_previous %}
            <li class="page-item ">
                <a class="page-link" href="?page={{posts.previous_page_number}}&q={{ request.GET.q }}">&laquo;</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link">&laquo;</a>
            </li>
        {% endif %}

        {% for i in posts.paginator.page_range %}

            {% if posts.number > 3 and forloop.first %}

                <li class="page-item disabled">
                <a class="page-link">...</a>

                </li>

            {% endif %}

            {% if posts.number == i %}
                <li class="page-item active">
                <a class="page-link">{{i}}</a>
                </li>
            {% elif i > posts.number|add:'-3' and i < posts.number|add:'3' %}
                <li class="page-item ">
                <a class="page-link" href="?page={{i}}&q={{ request.GET.q }}">{{i}}</a>
                </li>
            {% endif %}
        {% endfor %}

        {% if posts.paginator.num_pages > posts.number|add:'4' %}
            <li class='page-item'>
            <a class='page-link' href="?page={{ posts.number|add:'5' }}">&hellip;</a>
            </li>
            <li class='page-item'>
            <a class='page-link' href="?page={{ posts.paginator.count }}">{{ posts.paginator.count }}</a>
            </li>
        {% endif %}

        {% if posts.has_next %}
            <li class="page-item ">
                <a class="page-link" href="?page={{posts.next_page_number}}&q={{ request.GET.q }}">&raquo;</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link ">&raquo;</a>
            </li>
        {% endif %}
    {% endif %}

    </div>
</div>